- name: Install Packages using Scoop
  community.windows.win_scoop:
    gather_facts: true
    hosts: windows
    name: standardnotes
    global: true
  register: scoop_install_results
- name: Install Packages using Scoop Results
  debug:
    msg: "{{ scoop_install_results }}"
